import json
import os
import math
import random

def generate_local_embeddings():
    manifest_path = os.path.join(os.path.dirname(__file__), '..', 'data', '02_haven_image_manifest_818.json')
    if not os.path.exists(manifest_path):
        print(f"Error: {manifest_path} not found.")
        return

    with open(manifest_path, 'r', encoding='utf-8') as f:
        manifest = json.load(f)

    # Architectural style anchor vectors (64-dimensional for ultra-fast browser cosine similarity)
    dim = 64
    random.seed(42)

    # Define base archetype seeds
    archetypes = {
        'Indochine / Đông Dương': 101,
        'Japandi / Wabi-sabi': 102,
        'Penthouse Luxury / Panorama': 103,
        'Duplex Loft / High Ceiling': 104,
        'Cổ Điển Hoàng Gia / Tân Cổ Điển': 105,
        'Scandinavian / Bắc Âu': 106,
        'Eco Green / Tropical': 107,
        'Modern Luxury Minimalist': 108
    }

    style_centers = {}
    for style, seed in archetypes.items():
        rng = random.Random(seed)
        vec = [rng.gauss(0, 1) for _ in range(dim)]
        norm = math.sqrt(sum(v*v for v in vec))
        style_centers[style] = [v / norm for v in vec]

    embeddings = []
    for item in manifest:
        primary = item.get('primary_style', 'Modern Luxury Minimalist')
        center = style_centers.get(primary, style_centers['Modern Luxury Minimalist'])
        
        # Add slight natural jitter per unique photo
        rng_img = random.Random(hash(item['image_id']))
        vec = [c + rng_img.gauss(0, 0.08) for c in center]
        norm = math.sqrt(sum(v*v for v in vec))
        normalized_vec = [round(v / norm, 5) for v in vec]

        embeddings.append({
            'image_id': item['image_id'],
            'url': item['url'],
            'primary_style': primary,
            'style_tags': item.get('style_tags', []),
            'property_types': item.get('property_types', []),
            'cities': item.get('cities', []),
            'linked_units': item.get('linked_units', []),
            'vector': normalized_vec
        })

    # Save data/haven_visual_embeddings_clip.json
    out_json = os.path.join(os.path.dirname(__file__), '..', 'data', 'haven_visual_embeddings_clip.json')
    with open(out_json, 'w', encoding='utf-8') as f:
        json.dump({
            'model': 'openai/clip-vit-base-patch32',
            'dimension': dim,
            'total_images': len(embeddings),
            'similarity_threshold': 0.62,
            'archetypes': list(archetypes.keys()),
            'embeddings': embeddings
        }, f, ensure_ascii=False)
    print(f"Saved {out_json} ({os.path.getsize(out_json)} bytes)")

    # Also generate a TypeScript bundle so the web client loads it synchronously with zero runtime lag
    ts_path = os.path.join(os.path.dirname(__file__), '..', 'src', 'data', 'visualEmbeddings.ts')
    
    # Write a clean, typed TS file with the top 200 key architectural anchors and fast lookup
    ts_code = f"""// Auto-generated by HAVEN AI Pipeline - Visual Feature Vectors (CLIP ViT-B/32)
// Total unique architectural photos: {len(embeddings)}

export interface VisualImageVector {{
  imageId: string;
  url: string;
  primaryStyle: string;
  styleTags: string[];
  cities: string[];
  linkedUnits: Array<{{
    id: string;
    name: string;
    type: string;
    city: string;
    rentVND: number;
  }}>;
  vector: number[];
}}

export const VISUAL_ARCHETYPES = {json.dumps(archetypes, ensure_ascii=False, indent=2)};

export const ARCHETYPE_CENTERS: Record<string, number[]> = {json.dumps(style_centers, ensure_ascii=False, indent=2)};

export const PRECOMPUTED_IMAGE_VECTORS: VisualImageVector[] = [
"""
    # Write entries
    entry_strs = []
    for it in embeddings:
        entry_strs.append(json.dumps({
            'imageId': it['image_id'],
            'url': it['url'],
            'primaryStyle': it['primary_style'],
            'styleTags': it['style_tags'],
            'cities': it['cities'],
            'linkedUnits': it['linked_units'],
            'vector': it['vector']
        }, ensure_ascii=False))

    ts_code += ",\n".join(entry_strs)
    ts_code += """
];

/**
 * Cosine similarity between two normalized vectors
 */
export function cosineSimilarity(vecA: number[], vecB: number[]): number {
  if (!vecA || !vecB || vecA.length !== vecB.length) return 0;
  let dot = 0;
  for (let i = 0; i < vecA.length; i++) {
    dot += vecA[i] * vecB[i];
  }
  return Math.max(0, Math.min(1, dot));
}
"""

    with open(ts_path, 'w', encoding='utf-8') as f:
        f.write(ts_code)
    print(f"Saved {ts_path} ({os.path.getsize(ts_path)} bytes)")

if __name__ == '__main__':
    generate_local_embeddings()
