# -*- coding: utf-8 -*-
# List of 63 provinces and centrally-governed cities of Vietnam (and major cities)
PROVINCES_63 = [
    ("An Giang", "Long Xuyên"),
    ("Bà Rịa - Vũng Tàu", "Vũng Tàu"),
    ("Bắc Giang", "Bắc Giang"),
    ("Bắc Kạn", "Bắc Kạn"),
    ("Bạc Liêu", "Bạc Liêu"),
    ("Bắc Ninh", "Bắc Ninh"),
    ("Bến Tre", "Bến Tre"),
    ("Bình Định", "Quy Nhơn"),
    ("Bình Dương", "Thủ Dầu Một"),
    ("Bình Phước", "Đồng Xoài"),
    ("Bình Thuận", "Phan Thiết"),
    ("Cà Mau", "Cà Mau"),
    ("Cần Thơ", "Ninh Kiều"),
    ("Cao Bằng", "Cao Bằng"),
    ("Đà Nẵng", "Hải Châu"),
    ("Đắk Lắk", "Buôn Ma Thuột"),
    ("Đắk Nông", "Gia Nghĩa"),
    ("Điện Biên", "Điện Biên Phủ"),
    ("Đồng Nai", "Biên Hòa"),
    ("Đồng Tháp", "Cao Lãnh"),
    ("Gia Lai", "Pleiku"),
    ("Hà Giang", "Hà Giang"),
    ("Hà Nam", "Phủ Lý"),
    ("Hà Nội", "Ba Đình"),
    ("Hà Tĩnh", "Hà Tĩnh"),
    ("Hải Dương", "Hải Dương"),
    ("Hải Phòng", "Hồng Bàng"),
    ("Hậu Giang", "Vị Thanh"),
    ("Hòa Bình", "Hòa Bình"),
    ("Hưng Yên", "Hưng Yên"),
    ("Khánh Hòa", "Nha Trang"),
    ("Kiên Giang", "Rạch Giá"),
    ("Kon Tum", "Kon Tum"),
    ("Lai Châu", "Lai Châu"),
    ("Lâm Đồng", "Đà Lạt"),
    ("Lạng Sơn", "Lạng Sơn"),
    ("Lào Cai", "Lào Cai"),
    ("Long An", "Tân An"),
    ("Nam Định", "Nam Định"),
    ("Nghệ An", "Vinh"),
    ("Ninh Bình", "Ninh Bình"),
    ("Ninh Thuận", "Phan Rang - Tháp Chàm"),
    ("Phú Thọ", "Việt Trì"),
    ("Phú Yên", "Tuy Hòa"),
    ("Quảng Bình", "Đồng Hới"),
    ("Quảng Nam", "Tam Kỳ"),
    ("Quảng Ngãi", "Quảng Ngãi"),
    ("Quảng Ninh", "Hạ Long"),
    ("Quảng Trị", "Đông Hà"),
    ("Sóc Trăng", "Sóc Trăng"),
    ("Sơn La", "Sơn La"),
    ("Tây Ninh", "Tây Ninh"),
    ("Thái Bình", "Thái Bình"),
    ("Thái Nguyên", "Thành phố Thái Nguyên"),
    ("Thanh Hóa", "Thanh Hóa"),
    ("Thừa Thiên Huế", "Huế"),
    ("Tiền Giang", "Mỹ Tho"),
    ("TP. Hồ Chí Minh", "Quận 1"),
    ("Trà Vinh", "Trà Vinh"),
    ("Tuyên Quang", "Tuyên Quang"),
    ("Vĩnh Long", "Vĩnh Long"),
    ("Vĩnh Phúc", "Vĩnh Yên"),
    ("Yên Bái", "Yên Bái")
]

print(f"Total provinces: {len(PROVINCES_63)}")
